### PR TITLE
add support for static and dynamic remarketing tags

### PR DESCRIPTION
**Pull request by hankim813**
This resolves: https://segment.atlassian.net/browse/INT-647

Docs: 
- [Overview of Adwords Remarketing tags](https://developers.google.com/adwords-remarketing-tag/)
- [Asynchronous Remarketing tags](https://developers.google.com/adwords-remarketing-tag/asynchronous/#standard-javascript-use)

Important notes: 

Google states that you must fire remarketing tags in _addition_ to any conversion tags that might fire on the page.

> Although both tags look similar, the AdWords Remarketing Tag complements the AdWords Conversion Tag and does not replace it - you still need to use a AdWords Conversion Tag to successfully record conversions on your site's conversion pages, and you should also include the AdWords Remarketing Tag on the conversion page as well to record the remarketing data as well as the conversion. 

Static and Dynamic Remarketing options do not need to be separated because the only difference between the two is the _Dynamic_ tags passes in an _optional_ `google_custom_params` variable. If this is not provided (which denotes that the remarketing tag is static), you can still remarket based on the URLs. Given this information, `.page()` calls will pass in the `url` anyway through the its `props`, allowing you do generate rules inside Adwords whether they are dynamic or static.

The previous attempt to support this via this PR #8, we incorrectly _replaced_ the conversion tag with the remarketing tag. Now we will fire both if you have remarketing enabled.

I've also added more robust tests to validate these changes in behavior.

TODO: 
- [x] test extensively on staging
- [x] ship docs
- [x] deploy

@sperand-io @f2prateek @WesleyDRobinson @jgershen

### CODE REVIEW

**Comment by jgershen** [comment]
Have we now run e2e testing and seen conversion data successfully appearing in the test account?

**Comment by hankim813** [comment]
@jgershen not yet -- we'd need to get this merged and deployed to staging first but few blockers when we do:

1) we do not have an Adwords testing account
2) need to set up some ad campaigns and conversion labels 

^ We should take this opportunity to make a test account and put some $$$ in the ad budget.

**Comment by tsholmes** [comment]
Code change looks good. We should definitely set up an adwords account and see the right thing go through before shipping this.

**Comment by hankim813** [comment]
# End to end testing:

**Old version** after `.page()` with `remarketing = true`:



Note that you don't see props passed and no conversion request. So this was a poor implementation because pageview conversions were sent as remarketing tags NOT conversion tags this whole time. We were also not even passing the page properties w the remarketing tag.

**New version** after `.page()` with `remarketing = true`:



The above is a proper remarketing tag with properties being sent along. 

You can also now see below the conversion tag that fired as well to record the pageview conversion:



**Old version** after `.track()` with `remarketing = true`:



^ that is the conversion tag which is superfluously sending props even though conversion tags don't use that. Note no additional remarketing tag being fired here.

**New version** after `.track()` with `remarketing = true`:



^ is the proper remarketing tag which we did not see in the old version. also includes the properties as expected



^ And we still fire the same conversion tag in addition!

## In Adwords:

Conversion tag verified: 

```
(Conversion tag is active. Last seen:
Nov 16, 2016 at 5:03:41 PM (today)
```

Remarketing tag verified: 



@sperand-io @tsholmes @jgershen

**Pull request merged**
