### PR TITLE
Mark integration as ready only if the conversion script is loaded

### LINKED ISSUE #6: google_trackConversion is not a function
I see following exception on production:

`TypeError: window.google_trackConversion is not a function`

I've made a little investigation and I'm wondering, could it be possible that there is something wrong with an initialization?

I see some other integration initialize itself checking `loaded` state:
- https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L78
- https://github.com/segment-integrations/analytics.js-integration-qualaroo/blob/7baa8a10eceba4ce5530d8e89cedafe053c1eafb/lib/index.js#L33

### PR DESCRIPTION
**Pull request by ertrzyiks**
That most likely resolves #6

### CODE REVIEW

**Comment by kellyrmilligan** [comment]
Status on this? We're seeing this in our client side error tracking constantly

**Comment by ertrzyiks** [comment]
@kellyrmilligan I would like to know as well. Waiting for any response from contributors who can merge / resolve it in another way.

**Comment by ntotten** [comment]
I'd like to see this merged as well. We have this error show up hundreds of times a day.

**Comment by brennan** [comment]
@hankim813 @jgershen Do you guys have any thoughts on this PR?

**Review by tsholmes — APPROVED** [review]
It seems like the issue here is that `this.load` might be calling the callback if an adblocker blocks the adwords script from loading. Since we don't set up any stubs for the functions we're calling (like we do in most other integrations), it just ends up erroring out. This will work for now, so shipping it to unblock everyone using this integration.

**Comment by hankim813** [comment]
@tsholmes and everyone in this PR -- huge apologies from our team for letting this PR slip through the cracks. We're committed to upping our internal triaging of community submitted PRs so that you won't have to wait months before hearing back from our team!

With that said, we will ship this first tomorrow morning!

**Comment by hankim813** [comment]
@ertrzyiks @kellyrmilligan @ntotten @brennan @tsholmes deployed!

**Comment by ertrzyiks** [comment]
@hankim813 that's an awesome news, thanks! I see no more error with lack of `google_trackConversion`

**Pull request merged**
